Use better linter

diff --git a/.github/workflows/Check_CSV.yml b/.github/workflows/Check_CSV.yml
--- a/.github/workflows/Check_CSV.yml
+++ b/.github/workflows/Check_CSV.yml
@@ -1,6 +1,3 @@
-# S. https://github.com/marketplace/actions/csvlinter for details
-# CAUTION: does not catch ALL csv errors
-# Better linter: https://csvlint.io
 name: Check if CSV files are valid
 
 on: workflow_call
@@ -9,16 +6,37 @@ permissions:
   contents: read
 
 jobs:
-  test:
+  csvlint:
     runs-on: ubuntu-latest
-    name: csv lint
+
     steps:
-    - uses: actions/checkout@v4
-    - name: get_files
-      run: |
-        csv_files=$(find -type f -ipath ".*csv" -printf "%p ")
-        echo "CSV_FILES=$csv_files" >> $GITHUB_ENV
-    - name: csvlinter
-      uses: kcheriyath/csvlinter@V0.6.0
+    - name: Check out repository
+      uses: actions/checkout@v4
+
+    - name: Install Ruby #(csvlint.io is a Ruby gem)
+      uses: ruby/setup-ruby@v1
       with:
-        file_list: "${{ env.CSV_FILES }}"
+        ruby-version: '3.0'
+
+    - name: Install CSV Lint
+      run: gem install csvlint
+
+    - name: Lint all CSV files in the repository
+      shell: bash {0}
+      run: |
+        shopt -s globstar
+        shopt -s nocaseglob
+        for file in **/*.csv; do
+          csvlint $file
+          if [ $? -eq 0 ]; then
+            echo "File $file is valid"
+          else
+            echo "File $file is invalid"
+            echo "::error file=$file::File is invalid"
+            invalid_csv_found=true
+          fi
+        done
+        if [ "$invalid_csv_found" = true ] ; then
+          echo "At least one CSV file is invalid, failing the action"
+          exit 1
+        fi
